# Generated by Django 5.0.4 on 2024-04-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('registration', models.CharField(max_length=20, verbose_name='Registration')),
                ('office', models.CharField(max_length=100, verbose_name='Office')),
                ('photo', models.CharField(max_length=30, verbose_name='Foto')),
                ('isReady', models.BooleanField(verbose_name='Ready?')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
    ]
